import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create BlogWebsite",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
                <header className="p-4 bg-blue-500 text-white text-center">
                    <h1 className="text-2xl font-bold">Blog Website</h1>
                </header>
				<main className="p-6">{children}</main>
                <footer className="p-4 bg-blue-500 text-center">
                    <p>&copy; 2024 Blog Website. All rights reserved.</p>
                </footer>
			</body>
		</html>
	);
}
